# render.yaml

services:
  # 1. Serviço do Banco de Dados (Node.js)
  - type: web
    name: chatbot-db-service
    env: node
    plan: free
    dockerfilePath: ./Dockerfile.node
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: "file:./dev.db"


  - type: web
    name: chatbot-actions
    env: python
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .

    startCommand: "rasa run actions"
    healthCheckPath: /health
    envVars:
      - key: DB_SERVICE_URL
        fromService:
          type: web
          name: chatbot-db-service
          property: url
      - key: GEMINI_API_KEY
        fromSecretFile: .env


  - type: web
    name: chatbot-rasa
    env: python
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .

    startCommand: "rasa run --enable-api --cors \"*\""
    healthCheckPath: /
    envVars:
      - key: ACTIONS_SERVER_URL
        fromService:
          type: web
          name: chatbot-actions
          property: url