services:
  # Serviço 1: Banco de Dados PostgreSQL Gratuito
  # A Render vai gerenciar este banco de dados para você.
  - type: pserv
    name: chatbot-postgres-db
    plan: free
    region: oregon 

  # Serviço 2: API do Banco de Dados (Node.js)
  # Conecta-se ao banco de dados PostgreSQL criado acima.
  - type: web
    name: chatbot-db-api
    env: node 
    plan: free
    buildCommand: "npm install && npx prisma migrate deploy && npm run prisma:generate && npm run build"
    startCommand: "node dist/service.js"
    healthCheckPath: / 
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: chatbot-postgres-db
          property: connectionString
      - key: PORT 
        value: 3000

  # Serviço 3: Servidor de Ações do Rasa (Python)
  - type: web
    name: chatbot-actions
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile 
    healthCheckPath: /health
    dockerCommand: "rasa run actions"
    envVars:
      - key: GEMINI_API_KEY
        sync: false 
      - key: DATABASE_API_URL
        value: "http://chatbot-db-api:3000"

  # Serviço 4: Servidor Principal do Rasa (Python)
  - type: web
    name: chatbot-rasa-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile 
    healthCheckPath: / 
    envVars:
      - key: ACTION_ENDPOINT_URL
        value: "http://chatbot-actions:5055/webhook"