databases:
  - name: chatbot-postgres-db
    plan: free
    region: oregon

services:
  - type: web
    name: chatbot-db-api
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install && npx prisma migrate deploy && npm run prisma:generate && npm run build"
    startCommand: "node dist/service.js"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-postgres-db
          property: connectionString

  - type: web
    name: chatbot-actions
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile.actions
    startCommand: "rasa run actions -p $PORT"
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_API_URL
        value: "http://chatbot-db-api"

  - type: web
    name: chatbot-rasa-server
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ACTION_ENDPOINT_URL
        value: "http://chatbot-actions/webhook"