databases:
  - name: chatbot-postgres-db
    plan: free
    region: oregon

services:
  - type: web
    name: chatbot-db-api
    env: node 
    plan: free
    region: oregon
    buildCommand: "npm install && npx prisma migrate deploy && npm run prisma:generate && npm run build"
    startCommand: "node dist/service.js"
    healthCheckPath: / 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-postgres-db
          property: connectionString
      - key: PORT 
        value: 3000

  - type: web
    name: chatbot-actions
    startCommand: "rasa run actions -p $PORT"
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile 
    healthCheckPath: /health
    dockerCommand: "rasa run actions"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_API_URL
        value: "http://chatbot-db-api:3000"

  - type: web
    name: chatbot-rasa-server
    startCommand: "rasa run --enable-api --cors \"*\" -p $PORT"
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile 
    healthCheckPath: / 
    dockerCommand: "rasa run --enable-api --cors '*'"
    envVars:
      - key: ACTION_ENDPOINT_URL
        value: "http://chatbot-actions:5055/webhook"