services:
  - type: web
    name: chatbot-db-api
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/service.js"
    healthCheckPath: /

  - type: web
    name: chatbot-rasa-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: "rasa run --enable-api --cors \"*\" -p $PORT"


  - type: web
    name: chatbot-actions
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.actions
    startCommand: "rasa run actions -p $PORT"